---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ficoconx/vendor.ficoafrica.com # Update with your cPanel username and deployment path

    - npm install --production
    - npm run build

    - /bin/cp -R build/* $DEPLOYPATH

    - /usr/local/cpanel/bin/safeuserdatactl ficoconx enable
